import Head from "next/head";
import Content from "~/components/Content";
import Header from "~/components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Content/>
      </main>
    </>
  );
}